#!/bin/bash
sudo: required
services: docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - CONTAINER=misp-proxy
  - CONTAINER=misp-robot
  - CONTAINER=misp-server
  - PROXY_VERSION=1.0.0-alpine
  - PROXY_VERSION=1.0.0-ubuntu
  - ROBOT_VERSION=1.0.0-ubuntu
  - MISP_VERSION=2.4.88-ubuntu
  - MISP_VERSION=2.4.89-ubuntu

before_install:
    - pip install docker-ci-deploy==0.2.0
    #- git clone https://github.com/docker-library/official-images.git ~/official-images

install:
  - travis_retry container/build_for_travis.sh $CONTAINER

script:
  allow_failures:
    - make requirements
    #- make build-config:
    - docker run --name misp-robot-init --rm -ti -v $PWD:/srv/misp-dockerized dcso/misp-robot bash -c "scripts/build_config.sh --automated-build"
    - make deploy
    - make configure

  #- ~/official-images/test/run.sh "dcso/misp-server:$MISP_VERSION"

after_sucess:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: 
    # tag and push proxy alpine
    # using of dcd: -L latest -S version-semver -V version
    docker-ci-deploy --dry-run -L dcso/misp-proxy:$PROXY_VERSION
    docker-ci-deploy --dry-run -L dcso/misp-robot:$ROBOT_VERSION
    docker-ci-deploy --dry-run -L dcso/misp-server:$MISP_VERSION
  on:
    branch: master

  provider: script
  script: 
    # tag and push proxy alpine
    # using of dcd: -L latest -S version-semver -V version
    docker-ci-deploy --dry-run -L dcso/misp-proxy-private:$PROXY_VERSION
    docker-ci-deploy --dry-run -L dcso/misp-robot-private:$ROBOT_VERSION
    docker-ci-deploy --dry-run -L dcso/misp-server-private:$MISP_VERSION
  on:
    branch: develop
# vim:set et ts=2 sw=2: