version: '3.1'

### Networks ###
networks: 
  misp-backend:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: "mispbr0"
     com.docker.network.enable_ipv6: "false"
    ipam:
      config:
      - subnet: "192.168.47.0/28"


### Services ###
services:
  ### MISP Maria Database ###
  misp-db:
    image: dcso/misp-dockerized-db:10.4.5-bionic
    container_name: misp-db
    restart: unless-stopped
    volumes:
    - misp-vol-db-data:/var/lib/mysql
    networks:
      misp-backend:
        aliases:
        - misp-db 

  ### MISP Redis Server ###
  misp-redis:
    image: dcso/misp-dockerized-redis:5-alpine3.9
    restart: unless-stopped
    container_name: misp-redis
    command: ["redis-server", "--appendonly", "yes"] #For Data persistence
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) == PONG ] || exit 1"]
      interval: 1m30s
      timeout: 15s
      retries: 3
    volumes:
    - misp-vol-redis-data:/data
    networks:
      misp-backend:
        aliases:
        - misp-redis
  
  ### MISP Modules ###
  misp-modules:
    image: dcso/misp-dockerized-misp-modules:latest
    container_name: misp-modules
    restart: unless-stopped
    networks:
      misp-backend:
        aliases:
          - misp-modules

  ### MISP Server ###
  misp-server:
    image: dcso/misp-dockerized-server:2.4.112-debian
    container_name: misp-server
    restart: unless-stopped
    volumes:
    ###### mips-server ######
    # Apache2 Configuration
    - misp-vol-server-apache2-config-sites-enabled:/etc/apache2/sites-enabled
    # Volume with Certificates
    - misp-vol-ssl:/etc/apache2/ssl
    # Volume with PGP Key
    - misp-vol-pgp:/var/www/MISP/.gnupg
    # Volume with S/MIME Certificate and Key
    - misp-vol-smime:/var/www/MISP/.smime
    ###### misp-redis ######
    - misp-vol-redis-data:/redis_data_dir
    # MISP Configurations:
    - misp-vol-server-MISP-app-Config:/var/www/MISP/app/Config
    - misp-vol-server-MISP-cakeresque-config:/var/www/MISP/app/Plugin/CakeResque/Config
    - misp-vol-server-MISP-tmp:/var/www/MISP/app/tmp
    - misp-vol-server-MISP-attachments:/var/www/MISP/app/files
    networks:
      misp-backend:
        aliases:
        - misp-server

  ### Reverse Proxy ###
  misp-proxy:
    image: dcso/misp-dockerized-proxy:2
    container_name: misp-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"    
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
    volumes:
      # NGINX Configuration
      #- misp-vol-proxy-conf:/etc/nginx/conf.d
      # SSL 
      - misp-vol-ssl:/etc/nginx/ssl
    networks:
      misp-backend:
        aliases:
          - misp-nginx

  ### Robot ###
  misp-robot:
    image: dcso/misp-dockerized-robot:2
    container_name: misp-robot
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      disable: true
    volumes:
    ######  GLOBAL VOLUMES  ######
    # Docker.sock File
    - /var/run/docker.sock:/var/run/docker.sock:ro
    # Volume with Certificates
    - misp-vol-ssl:/srv/misp-ssl
    # Volume with PGP Key
    - misp-vol-pgp:/srv/misp-pgp
    # Volume with S/MIME Certificate and Key
    - misp-vol-smime:/srv/misp-smime
    ###### mips-server ######
    - misp-vol-server-apache2-config-sites-enabled:/srv/misp-server/apache2/sites-enabled
    - misp-vol-server-MISP-app-Config:/srv/misp-server/MISP/Config
    - misp-vol-server-MISP-cakeresque-config:/srv/misp-server/MISP/CakeResque/Config
    - misp-vol-server-MISP-tmp:/srv/misp-server/MISP/app/tmp
    - misp-vol-server-MISP-attachments:/srv/misp-server/MISP/app/files
    ###### misp-proxy ######
    - misp-vol-proxy-conf:/srv/misp-proxy/conf.d
    ###### misp-redis ######
    - misp-vol-redis-data:/srv/misp-redis
    ###### misp-db ######
    - misp-vol-db-data:/srv/misp-db
    networks:
      misp-backend:
        aliases:
          - misp-robot

  ### Monitoring ###
  misp-monitoring:
    image: dcso/misp-dockerized-monitoring:latest
    container_name: misp-monitoring
    restart: unless-stopped
    # ports:
    #   - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - misp-vol-netdata-cache:/var/cache/netdata
    networks:
      misp-backend:
        aliases:
          - misp-monitoring


### VOLUMES ###
volumes:
  misp-vol-ssl:
  misp-vol-pgp:
  misp-vol-smime:
  misp-vol-db-data:
  misp-vol-redis-data:
  misp-vol-server-apache2-config-sites-enabled:
  misp-vol-server-MISP-app-Config:
  misp-vol-server-MISP-cakeresque-config:
  misp-vol-server-MISP-tmp:
  misp-vol-server-MISP-attachments:
  misp-vol-proxy-conf:
  misp-vol-netdata-cache:
