image: docker:latest

services:
  - docker:dind

stages:
- build
- deploy

variables:
  #CONTAINER_TEST_IMAGE: my-docker-hub/$CI_PROJECT_ID:$CI_BUILD_REF_NAME_test
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_TOKEN
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # INTERNAL_REGISTRY_HOST
  # INTERNAL_REGISTRY_USER
  # INTERNAL_REGISTRY_PW
  DOCKER_COMPOSE_VERSION: 1.22.0

before_script:
  - apk add --no-cache make bash sudo git curl python py2-pip
  - export makefile="make -C .travis/"
  - export CI="true"
  - export REPOURL="dockerhub.dcso.de"
  - docker login -u "$INTERNAL_REGISTRY_USER" -p "$INTERNAL_REGISTRY_PW" "$INTERNAL_REGISTRY_HOST"
  # https://stackoverflow.com/questions/42295457/using-docker-compose-in-a-gitlab-ci-pipeline
  - pip install --no-cache-dir docker-compose
  # download latest images from registry
  - $makefile pull-latest REPOURL=${REPOURL}


Short_Test_without_Push:
  stage: build
  except:
  - master
  - unstable
  script:
  - make build-config
  - docker-compose -v
  - docker-compose pull
  - echo "############################################# START with make install "#############################################"
  # start deploy script
  - make install

Long_Test_without_Push:
  stage: build
  only:
  - unstable
  script:
  # download latest images from registry
  - $makefile pull-latest REPOURL=${REPOURL}
  - ./docker-compose pull
  # start deploy script
  - make install
  # test if MISP is ready
  - $makefile test

Upload_2_Repository:
  stage: build
  only: 
  - master
  script:
  # download latest images from registry
  - $makefile pull-latest REPOURL=${REPOURL}
  - docker-compose pull
  # start deploy script
  - make install
  # test if MISP is ready
  - $makefile test
  # prepare retagging
  - export server_tag=$(cat .env |grep MISP_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export proxy_tag=$(cat .env |grep PROXY_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export robot_tag=$(cat .env |grep ROBOT_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export postfix_tag=$(cat .env |grep POSTFIX_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export postfix_tag=$(cat .env |grep POSTFIX_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export modules_tag=$(cat .env |grep MISP_MODULES_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  # retag all existing tags dev 2 public repo
  - $makefile tag server_tag=${server_tag} proxy_tag=${proxy_tag} robot_tag=${robot_tag} postfix_tag=${postfix_tag} modules_tag=${modules_tag}
  # Push Images to registry
  - $makefile push server_tag=${server_tag} proxy_tag=${proxy_tag} robot_tag=${robot_tag} postfix_tag=${postfix_tag} modules_tag=${modules_tag} REPOURL=${REPOURL};
