image: gitlab.dcso.lolcat:4567/misp/helper-containers:docker
#image: docker:latest

services:
  - docker:dind

stages:
- test
- scan
- build
- unsupported

variables:
  # The following variables are setup via gitlab project group:
    # DOCKER_SLUG
    # DOCKER_USERNAME
    # DOCKER_PASSWORD
    # CUSTOM_REGISTRY_URL
    # CUSTOM_REGISTRY_USER
    # CUSTOM_REGISTRY_PW
  # Set via Job:
    # CURRENT_VERSION
  # DOCKER_HOST: docker:2376
  # DOCKER_TLS_VERIFY: 1
  DOCKER_DRIVER: overlay2
  #DOCKER_TLS_CERTDIR: ""


before_install:
#- docker info
# Include Variables
- source .ci/00_vars.sh
# Install dependencies
#- .ci/01_before_install.sh
- git config --global user.name "MISP-dockerized-bot"

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine
  before_install:
    - echo "Override default before_script"
  script:
    - find . -path "*.sh" -type f -print -exec shellcheck {} +
  allow_failure: true     # If you would check via shellcheck, but not to fail it there is any found.

.env_test_only:
  stage: test
  tags:
  - dind
  except:
  - master
  - dev
  - v1.2.0
  script:
    # Test
  - make -C .ci script REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD TEST=no_test VERSION=$CURRENT_VERSION
    # Clean Up
  - echo "##### clean up..." &&  make delete


# On dev Branch: Build Environment and Test it with our own Test Framework
.long_test:
  stage: test
  tags:
  - dind
  only:
  - dev
  - v1.2.0
  script:
  #   # Test
  # - make -C .ci script REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD TEST=long_test VERSION=$CURRENT_VERSION
  #   # Tag 
  # - make -C .ci tag REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
    # Clean Up
  - echo "##### clean up..." &&  make -C $FOLDER delete
  # https://docs.gitlab.com/ee/ci/yaml/README.html#artifacts-reports
  artifacts:
    paths: 
    - .ci/reports/*
    reports:
      junit: .ci/reports/*.xml


.push_productive_images:
  stage: build
  tags:
  - dind
  only: 
  - master
  - schedules
  - v1.2.0
  before_script:
    # Test
  - make -C .ci script REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD TEST=long_test VERSION=$CURRENT_VERSION
    # Tag 
  - make -C .ci tag REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
  script:
    # Push 
  - make -C .ci push REPOURL=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
    # Clean Up
  - echo "##### clean up..." &&  make -C $FOLDER delete
  # https://docs.gitlab.com/ee/ci/yaml/README.html#artifacts-reports
  artifacts:
    paths: 
    - ./.ci/reports/*
    reports:
      junit: ./.ci/reports/*.xml
      

.container_scanning:
  # https://docs.gitlab.com/ee/ci/examples/container_scanning.html
  # https://docs.gitlab.com/ee/ci/yaml/README.html#artifactsreportscontainer_scanning
  # https://docs.gitlab.com/ee/user/project/merge_requests/container_scanning.html
  # https://docs.gitlab.com/ee/ci/yaml/#artifactsreportscontainer_scanning-ultimate
  stage: scan
  tags:
  - dind
  variables:
    DOCKER_DRIVER: overlay2
    ## Define two new variables based on GitLab's CI/CD predefined variables
    ## https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables
  allow_failure: true
  script:
  - bash .ci/10_scanning.sh
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json


include:
  - '.gitlab-unsupported.yml'
  #- '0.1.0/.gitlab-ci.yml'
  #- '0.1.1/.gitlab-ci.yml'
  #- '0.1.2/.gitlab-ci.yml'
  #- '0.2.0/.gitlab-ci.yml'
  #- '0.3.0/.gitlab-ci.yml'
  #- '0.3.1/.gitlab-ci.yml'
  #- '0.3.2/.gitlab-ci.yml'
  #- '0.3.3/.gitlab-ci.yml'
  #- '0.3.4/.gitlab-ci.yml'
  #- '1.0.0/.gitlab-ci.yml'
  #- '1.0.1/.gitlab-ci.yml'
  #- '1.0.2/.gitlab-ci.yml'
  - '1.0.3/.gitlab-ci.yml'
  #- '1.1.0/.gitlab-ci.yml'
  - '1.1.1/.gitlab-ci.yml'
  - '1.2.0/.gitlab-ci.yml'
