#!/bin/bash
sudo: required
services: docker

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - make requirements
  - docker run --name misp-robot-init --rm -ti -v $PWD:/srv/misp-dockerized dcso/misp-robot bash -c "scripts/build_config.sh --automated-build"
  - make deploy
  - make configure
script:
  - echo "$(curl -S -k https://localhost/users/login|grep Login)"

# vim:set et ts=2 sw=2: