#!/bin/bash
sudo: required
services: docker

env:
  global:
  # Docker Username only valid for this repo
  - secure: "UVqDqQ5UFX8kzaU3wxFg0BUr2Cq0dh4BvuGl2krMkfHPWIseZZYAqctqCvQffKUROD+h+sCALepQZX4ZKsi2a08OJclv6TN8Eri2A3i5dYfBbeZ6rHq4e18bm+dEi00VYbqKMvz0SewqlewpowrKdfnLsO9ZvPr8pdKLWWqCdK90Id/OeQKs+THDtFcshqdtNrDaDBqQsZqWX58oLXzT6jio6hAlIh3MmSRFrx3nplLM5P9xJ3gKy1BIhs+3G26UfTrVxjuwCEsvhpWB52735INkA4vxunHZT/vbP+WDkI3am//pFz6Xg0F+9l8LepaTYT2Ksowq8GZD5lKLnfhknJOvyRhGWiV2k6SYz7cnW66RK630G588O9oa0ol3HnjQYCW9PNnQn11EZUBpcf2BVFEi4k/OGtJarv2dAI9LjLDerMKdHDpVqlAINLlWNrCwgxmg682SvsiEQwurxux9WEcMQacPU0ruTdV6GGgZdu67NEBkOP+Wcn/6ZjVXrPTXCDBSMOO/DVLd/HJyCCs3wkusf7/bdcG5Fta8DSW25VY8pZzfFVG1m5yAvl/Ndgl0wiHfsEUuhLK/TkUOOtFlSspbtnWXG1qzlJOWuFEBS6f5MogOJxQU17gJmCLHg9qvoR/tMv5UfezziwXn7m3mRagy1FMBG9VFf6ri6BR7XC8="
  # Docker Password only valid for this repo
  - secure: "DbvcY54cCCFfCNcqGNL4leThq/a9HTCVf5dj4hX7LKgh7xi9UYWVE9y/v/3i9kmVvptDu4c3xkUw1hKaLXIMJ0xSRvzJMtMQTz4awlymJmYXyJrV1Hvy6O+Xq961xff/gFSLYvntomlhDiA3f5e2VGYLacrVXExyQdy/uvy0I23ceyFgcRb2U0iRuBscWyvvXLyTYtvQFFnMlGwxXl789YK6YYIKf30AOZ6Q7ffm4VRPJ+ppRxJk4HxglBHcE+Ez81OW9PdXJTsUSBw8UcS0ZV7tD1cSOwL3lTCdlVYKEwDnSwIYLbXnnBhm4aG0L2flJ4hHUUk6TIQGTHtG2Z9wihLEjeEqLGg9vr9xE0XJdaL2stM6UgLJa9Oyb2Zl3UUQeaxkXU0LDWnwOBvamGhhWvHWi6qvVOh011Qb7WlLZcBY+Di+EGellb4NG8MvLmU0K0DEUQuCpi9yz5opiy1TYgZwNLBwRcX15nc3ePaqKLPkH5SQxFPMY9DkOpgtGNda7HRkEZ9Zy0d2MizzmS6/PfTKXQOzJordnWJdZ8lPh2mZmPN0Jpv4WsJZtszN+airztCeC0pkkkOurRI1Cz+cxky15QtfOPbuC7/3OCi60m5SoYxqNN172PdCZQdO2VY25YTTRiExLBJkA/Xwmc0b0DZ2maTownJX3yi8HOAhKcA="
  - FOLDER="./current/"
  - MAKE_OPTION="-C $FOLDER"
  - makefile_main="make -C $FOLDER"
  - DOCKER_COMPOSE_OPTION="-f $FOLDERdocker-compose"
  - makefile_travis="make -C $FOLDER.travis/"
  matrix:
  #- VERSION=0.1.2
  #- VERSION=0.2.0
  #- VERSION=0.3.4
  - VERSION=1.0.0
  - VERSION=1.0.1
  - VERSION=1.0.2

before_install:
  # create current directory
  - ./FOR_NEW_INSTALL.sh $VERSION
  # update docker etc.
  - travis_retry ./$VERSION/.travis/main.sh
  # pull all images 
  - travis_retry $makefile_travis pull-latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;

script:
  # Install and configure MISP
  - $makefile_main install
  - ls -la config/*/
  # test if MISP is ready
  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then $makefile_travis test; fi

after_success:
  - export server_tag=$(cat $FOLDER/docker-compose.yml |grep image|grep server|cut -d ':' -f 3)
  - export proxy_tag=$(cat $FOLDER/docker-compose.yml |grep image|grep proxy|cut -d ':' -f 3)
  - export robot_tag=$(cat $FOLDER/docker-compose.yml |grep image|grep robot|cut -d ':' -f 3)
  #- export postfix_tag=$(cat $FOLDER/docker-compose.yml |grep image|grep server|cut -d ':' -f 3)
  - export modules_tag=$(cat $FOLDER/docker-compose.yml |grep image|grep modules|cut -d ':' -f 3)
  - export db_tag=$(cat $FOLDER/docker-compose.yml |grep image|grep db|cut -d ':' -f 3)
  - export redis_tag=$(cat $FOLDER/docker-compose.yml |grep image|grep redis|cut -d ':' -f 3)
  # retag all existing tags dev 2 public repo
  - $makefile_travis tag server_tag=${server_tag} proxy_tag=${proxy_tag} robot_tag=${robot_tag} postfix_tag=${postfix_tag} modules_tag=${modules_tag} db_tag=${modules_tag} redis_tag=${modules_tag}
  # check if branch=master and the current build is no pull request, then push it to docker hub
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
      if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
        $makefile_travis push server_tag=${server_tag} proxy_tag=${proxy_tag} robot_tag=${robot_tag} postfix_tag=${postfix_tag} modules_tag=${modules_tag};
      fi; 
    fi;

# don't notify me when things fail
notifications:
  email: false