dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  matrix:
  #- VERSION=0.1.2
  #- VERSION=0.2.0
  #- VERSION=0.3.4
  - VERSION=1.0.0
  - VERSION=1.0.1
  - VERSION=1.0.2

before_install:
- source .ci/00_vars.sh
- .ci/01_before_install.sh

script:
- bash .ci/02_script.sh

deploy:
  provider: script
  script: bash .ci/30_push_2_registry.sh
  on:
    branch: master

# don't notify me when things fail
notifications:
  email: false