#!/bin/bash
sudo: required
services: docker

env:
  global:
  # Docker Username only valid for this repo
  - secure: "UVqDqQ5UFX8kzaU3wxFg0BUr2Cq0dh4BvuGl2krMkfHPWIseZZYAqctqCvQffKUROD+h+sCALepQZX4ZKsi2a08OJclv6TN8Eri2A3i5dYfBbeZ6rHq4e18bm+dEi00VYbqKMvz0SewqlewpowrKdfnLsO9ZvPr8pdKLWWqCdK90Id/OeQKs+THDtFcshqdtNrDaDBqQsZqWX58oLXzT6jio6hAlIh3MmSRFrx3nplLM5P9xJ3gKy1BIhs+3G26UfTrVxjuwCEsvhpWB52735INkA4vxunHZT/vbP+WDkI3am//pFz6Xg0F+9l8LepaTYT2Ksowq8GZD5lKLnfhknJOvyRhGWiV2k6SYz7cnW66RK630G588O9oa0ol3HnjQYCW9PNnQn11EZUBpcf2BVFEi4k/OGtJarv2dAI9LjLDerMKdHDpVqlAINLlWNrCwgxmg682SvsiEQwurxux9WEcMQacPU0ruTdV6GGgZdu67NEBkOP+Wcn/6ZjVXrPTXCDBSMOO/DVLd/HJyCCs3wkusf7/bdcG5Fta8DSW25VY8pZzfFVG1m5yAvl/Ndgl0wiHfsEUuhLK/TkUOOtFlSspbtnWXG1qzlJOWuFEBS6f5MogOJxQU17gJmCLHg9qvoR/tMv5UfezziwXn7m3mRagy1FMBG9VFf6ri6BR7XC8="
  # Docker Password only valid for this repo
  - secure: "DbvcY54cCCFfCNcqGNL4leThq/a9HTCVf5dj4hX7LKgh7xi9UYWVE9y/v/3i9kmVvptDu4c3xkUw1hKaLXIMJ0xSRvzJMtMQTz4awlymJmYXyJrV1Hvy6O+Xq961xff/gFSLYvntomlhDiA3f5e2VGYLacrVXExyQdy/uvy0I23ceyFgcRb2U0iRuBscWyvvXLyTYtvQFFnMlGwxXl789YK6YYIKf30AOZ6Q7ffm4VRPJ+ppRxJk4HxglBHcE+Ez81OW9PdXJTsUSBw8UcS0ZV7tD1cSOwL3lTCdlVYKEwDnSwIYLbXnnBhm4aG0L2flJ4hHUUk6TIQGTHtG2Z9wihLEjeEqLGg9vr9xE0XJdaL2stM6UgLJa9Oyb2Zl3UUQeaxkXU0LDWnwOBvamGhhWvHWi6qvVOh011Qb7WlLZcBY+Di+EGellb4NG8MvLmU0K0DEUQuCpi9yz5opiy1TYgZwNLBwRcX15nc3ePaqKLPkH5SQxFPMY9DkOpgtGNda7HRkEZ9Zy0d2MizzmS6/PfTKXQOzJordnWJdZ8lPh2mZmPN0Jpv4WsJZtszN+airztCeC0pkkkOurRI1Cz+cxky15QtfOPbuC7/3OCi60m5SoYxqNN172PdCZQdO2VY25YTTRiExLBJkA/Xwmc0b0DZ2maTownJX3yi8HOAhKcA="
  - makefile="make -C .travis/"


before_install:
  - travis_retry .travis/main.sh
  # pull all images 
  - travis_retry $makefile pull-latest

script:
  # Install and configure MISP
  - make install
  - ls -la config/*/
  # test if MISP is ready
  - if [[ "$TRAVIS_BRANCH" == "unstable" ]]; then $makefile test; fi

after_success:
  - export server_tag=$(cat .env |grep MISP_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export proxy_tag=$(cat .env |grep PROXY_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export robot_tag=$(cat .env |grep ROBOT_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export postfix_tag=$(cat .env |grep POSTFIX_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  - export modules_tag=$(cat .env |grep MISP_MODULES_CONTAINER|cut -d = -f 2|sed 's,....$,,')
  # retag all existing tags dev 2 public repo
  - $makefile tag server_tag=${server_tag} proxy_tag=${proxy_tag} robot_tag=${robot_tag} postfix_tag=${postfix_tag} modules_tag=${modules_tag}
  # check if branch=master and the current build is no pull request, then push it to docker hub
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
      if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
        $makefile push server_tag=${server_tag} proxy_tag=${proxy_tag} robot_tag=${robot_tag} postfix_tag=${postfix_tag} modules_tag=${modules_tag};
      fi; 
    fi;

# don't notify me when things fail
notifications:
  email: false