version: '3.1'


networks: 
  misp-backend:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: "mispbr0"
     com.docker.network.enable_ipv6: "false"
    #internal: true
    ipam:
      config:
      - subnet: "192.168.47.0/28"

services:
  ### Postfix ###
  # https://hub.docker.com/_/nginx/
  misp-postfix:
    image: dcso/misp-dockerized-postfix:${POSTFIX_CONTAINER_TAG}
    container_name: misp-postfix
    restart: on-failure
    environment:
      HOSTNAME: ${HOSTNAME}
      DOMAIN: ${DOMAIN}
      SENDER_ADDRESS: ${SENDER_ADDRESS}
      RELAYHOST: ${RELAYHOST}
      RELAY_USER: ${RELAY_USER}
      RELAY_PASSWORD: ${RELAY_PASSWORD}
      DOCKER_NETWORK: ${DOCKER_NETWORK}
      DEBUG_PEER: ${DEBUG_PEER}
    networks:
      misp-backend:
        aliases:
          - misp-postfix

  ### MISP Apache Server ###    
  misp-server:
    image: dcso/misp-dockerized-server:${MISP_CONTAINER_TAG}
    container_name: misp-server
    depends_on:
      - "misp-postfix"
    restart: on-failure  
    tty: true
    stdin_open: true
    # ports:
    #   - "8080:80" # DEBUG only
    #   - "8443:443" # DEBUG only
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      CMD_MYSQL: mysqld
      CMD_APACHE:
      CMD_REDIS: redis-server --appendonly yes
    volumes:
    # DB
    - misp-vol-db-data:/var/lib/mysql/
    # Logfile
    - misp-vol-server-logs:/var/log/apache2/
    # Apache2 Configuration
    - misp-vol-server-apache2-config-sites-enabled:/etc/apache2/sites-enabled:ro
    - misp-vol-ssl:/etc/apache2/ssl:ro
    # MISP Configurations:
    - misp-vol-server-MISP-app-Config:/var/www/MISP/app/Config
    - misp-vol-server-MISP-cakeresque-config:/var/www/MISP/app/Plugin/CakeResque/Config
    - misp-vol-server-MISP-tmp:/var/www/MISP/tmp
    - misp-vol-server-MISP-attachments:/var/www/MISP/attachments
    networks:
      misp-backend:
        aliases:
        - misp-server

  ### Reverse Proxy ###
  # https://hub.docker.com/_/nginx/
  misp-proxy:
    image: dcso/misp-dockerized-proxy:${PROXY_CONTAINER_TAG}
    container_name: misp-proxy
    depends_on:
      - "misp-server"
    restart: on-failure
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"    
    volumes:
      # NGINX Configuration
      - misp-vol-proxy-conf:/etc/nginx/conf.d:ro
      # NGINX SSL 
      - misp-vol-ssl:/etc/nginx/ssl:ro
    networks:
      misp-backend:
        aliases:
          - misp-nginx

  ### Robot ###
  misp-robot:
    image: dcso/misp-dockerized-robot:${ROBOT_CONTAINER_TAG}
    container_name: misp-robot
    depends_on:
      - "misp-server"
      - "misp-proxy"
    tty: true
    stdin_open: true
    healthcheck:
      disable: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro                    # docker.sock | Make sure its always read only!
    - myHOST_PATH:/srv/misp-dockerized              # Github Repository
    - misp-vol-ssl:/srv/misp-ssl
    - misp-vol-server-apache2-config-sites-enabled:/srv/misp-server/apache2/sites-enabled
    - misp-vol-server-MISP-app-Config:/srv/misp-server/MISP/Config
    - misp-vol-server-MISP-cakeresque-config:/srv/misp-server/MISP/CakeResque/Config
    - misp-vol-server-MISP-tmp:/srv/misp-server/MISP/tmp
    - misp-vol-server-MISP-attachments:/srv/misp-server/MISP/attachments
    - misp-vol-proxy-conf:/srv/misp-proxy/conf.d
    - myHOST_PATH/playbooks:/etc/ansible/playbooks/robot-playbook:ro
    - myHOST_PATH/scripts:/srv/scripts:ro
    networks:
      misp-backend:
        aliases:
          - misp-robot

### VOLUMES ###
volumes:
  misp-vol-ssl:
  misp-vol-db-data:
  misp-vol-redis-data:
  misp-vol-server-logs:
  misp-vol-server-apache2-config-sites-enabled:
  misp-vol-server-MISP-app-Config:
  misp-vol-server-MISP-cakeresque-config:
  misp-vol-server-MISP-tmp:
  misp-vol-server-MISP-attachments:
  misp-vol-proxy-conf:
