#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
TAGS="$(git tag -l|tail +2)"                        # existing commits
myCOMMIT="$(git log --format="%H"|head -1)"         # my currently installed commit
myTAG=""                                            # my current installed tag
########################################
source ./configuration.sh
########################################
# Function: Search in git repo my Installed Tag
function search_myTag(){
  # search existing tag
  
  # END
  for TAG in $TAGS
  do
    COMMIT=$(git log "$TAG" --format="%H"|head -1)
    if [ "$myCOMMIT" == "$COMMIT" ]; then myTAG+="$TAG"; fi
  done
}
# execute function:
search_myTag

for TAG in $myTAG
do
    # Tag the latest build with all existing git tags with the same commit. 
    # After this Push the tag in addition to the "latest" tag already pushed.
    docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
    docker push $DOCKER_REPO:$TAG
done

# Invoke all downstream build triggers.
for url in $(echo $NEXT_BUILD_TRIGGERS | sed "s/,/ /g")
do
    curl -X POST $url
done