##### Copy MISP configs #####
- name: Configure MISP | Copy MISP configuration files
  copy:
    remote_src: True
    src: "{{MISP_PATH}}/Config/{{ item }}.default.php"
    dest: "{{MISP_PATH}}/Config/{{ item }}.php"
    force: yes
    owner: www-data
    group: www-data
    mode: 0750
  with_items:
    - bootstrap
    - database
    - core
    - config

#### Write settings #####
- name: Configure MISP | Set DB User, Password and Host
  replace:
    name: "{{MISP_PATH}}/Config/database.php"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    owner: www-data
    group: www-data
  with_items:
  - { regexp: "db password", replace: "{{ MYSQL_PASSWORD }}" }
  - { regexp: "db login", replace: "{{ MYSQL_USER }}" }
  - { regexp: "localhost", replace: "{{ MYSQL_HOST }}" }

- name: Configure MISP | Set MISP-Url
  replace:
    name: "{{MISP_PATH}}/Config/config.php"
    regexp: "'baseurl'\\s*=>\\s*''"
    replace: "'baseurl'                        => 'https://{{ MISP_hostname }}:{{ MISP_hostport }}'"
    owner: www-data
    group: www-data

- name: Configure MISP | Set Redis URL
  replace:
    name: "{{MISP_PATH}}/CakeResque/Config/config.php"
    regexp: "'host'\\s*=>\\s*'localhost'" # 'host' => 'misp-redis'
    replace: "'host' => '{{ REDIS_hostname }}'"
    owner: www-data
    group: www-data

##### Check permissions #####
- name: Configure MISP | Check permissions
  file:
    path: "{{ item.file }}"
    owner: www-data
    group: www-data
    mode: "{{ item.mode }}"
  with_items:
  - {file: "{{MISP_PATH}}", mode: "0750" }
  - {file: "{{MISP_PATH}}/tmp", mode: "g+ws" }
  - {file: "{{MISP_PATH}}/attachments", mode: "g+ws" }
  # - {file: "{{MISP_PATH}}/files", mode: "g+ws" }
  # - {file: "{{MISP_PATH}}/app/files/scripts/tmp", mode: "g+ws" }

##### Configure SSL #####
- include: tasks/ssl.yml

# - name: Apache2 | Activate SSL config
#   copy:
#     src: "{{SERVER_CONFIG_PATH}}/misp.ssl.conf"
#     dest: "{{SERVER_CONFIG_PATH}}/sites-enabled/misp.ssl.conf"
#     force: yes
#     owner: root
#     group: root
#     mode: 0640

- name: Apache2 | Create & activate SSL configuration
  template:
    src: template/{{ item }}.j2
    dest: "{{ SERVER_CONFIG_PATH }}/{{ item }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - misp.ssl.conf

##### restart Docker Container #####
- name: Apache2 | Restart Apache2 docker container
  # docker_container:
  #   name: misp-server
  #   state: started
  #   restart: yes
  shell: docker restart misp-server