##### Configure SSL #####
- include: tasks/ssl.yml

##### Configure NGINX #####
- name: Proxy | check if HTTP config files exists
  stat: 
    path: "{{SSL_CONFIG_PATH}}/{{HTTP_CONFIG_NAME}}.conf"
  register: server_http

- name: Proxy | check if HTTPS config files exists
  stat: 
    path: "{{SSL_CONFIG_PATH}}/{{HTTPS_CONFIG_NAME}}.conf"
  register: server_https

- name: Proxy | activate https config to proxy
  copy:
    src: "files/conf.d/{{ item }}.conf"
    dest: "{{SERVER_CONFIG_PATH}}/{{ item }}.conf"
    force: yes
    owner: root
    group: root
    mode: 0640
  with_items:
    - "{{HTTPS_CONFIG_NAME}}"
  when: server_https.stat.exists is defined and server_https.stat.exists == False

- name: Proxy | deactivate http config
  shell: "{{ item }}"
  with_items:
    - "mv {{SERVER_CONFIG_PATH}}/{{HTTP_CONFIG_NAME}}.conf {{SERVER_CONFIG_PATH}}/{{HTTP_CONFIG_NAME}}"
  when: server_http.stat.exists is defined and server_http.stat.exists

- name: Proxy | copy template for Allowed IPs
  template:
    src: "template/{{ item }}.j2"
    dest: "{{SERVER_CONFIG_PATH}}/{{ item }}"
    force: yes
    owner: root
    group: root
    mode: '0644'
  with_items:
  - GLOBAL_allow_IPs
  when: ALLOW_ALL_IPs is defined and ALLOW_ALL_IPs == "yes"

- name: Proxy | update vars_common file
  template:
    src: "template/{{ item }}.j2"
    dest: "{{SERVER_CONFIG_PATH}}/{{ item }}"
    force: yes
    owner: root
    group: root
    mode: '0644'
  with_items:
  - vars_common

##### restart Docker Container #####
- name: Proxy | Restart proxy
  shell: docker restart misp-proxy
