env_test_only 1.1.1:
  variables:
    CURRENT_VERSION: 1.1.1
  extends: .env_test_only
  # only:
  #   changes:
  #     - 1.1.1/*

long_test 1.1.1:
  variables:
    CURRENT_VERSION: 1.1.1
  extends: .long_test
  # only:
  #   changes:
  #     - 1.1.1/*

push_productive_images 1.1.1:
  variables:
    CURRENT_VERSION: 1.1.1
  extends: .push_productive_images
  # only:
  #   changes:
  #     - 1.1.1/*

# scan proxy:
#   variables:
#     CI_CONTAINER_NAME: misp-dockerized-proxy
#     #CI_APPLICATION_TAG: 
#   extends: .container_scanning

# scan robot:
#   variables:
#     CI_CONTAINER_NAME: misp-dockerized-robot
#     #CI_APPLICATION_TAG: 
#   extends: .container_scanning

# scan server:
#   variables:
#     CI_CONTAINER_NAME: misp-dockerized-server
#     #CI_APPLICATION_TAG: 
#   extends: .container_scanning

# scan modules:
#   variables:
#     CI_CONTAINER_NAME: misp-dockerized-misp-modules
#     #CI_APPLICATION_TAG: 
#   extends: .container_scanning