---
- name: MISP Installation Script for Docker
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  #vars:
    #DB_PW_MISP: lookup('env', 'VAR')
    #DB_PW_ROOT: lookup('env', 'VAR')
    #SERVER_FQDN: lookup('env', 'VAR')

  vars_files:
    - "/srv/misp-config/misp.conf.yml"  

  roles:
  - role: server
    tags: ['server']
  - role: database
    tags: ['database']
  - role: proxy
    tags: ['proxy']