##### MISP configs #####
- import_tasks: misp.yml

##### Configure SSL #####
- include: tasks/ssl.yml

##### PGP configs #####
- import_tasks: pgp.yml

##### S/MIME configs #####
- import_tasks: smime.yml


- name: Apache2 | Disable standard MISP config
  shell: "mv {{ SERVER_CONFIG_PATH }}/misp.conf {{ SERVER_CONFIG_PATH }}/misp"
  ignore_errors: True

- name: Apache2 | Enable SSL MISP config
  shell: "mv {{ SERVER_CONFIG_PATH }}/misp.ssl {{ SERVER_CONFIG_PATH }}/misp.ssl.conf"
  ignore_errors: True


# - name: Apache2 | Create & activate SSL configuration
#   template:
#     src: template/{{ item }}.j2
#     dest: "{{ SERVER_CONFIG_PATH }}/{{ item }}"
#     owner: root
#     group: root
#     mode: 0640
#   with_items:
#     - misp.ssl.conf


##### restart Docker Container #####
- name: Apache2 | Restart Apache2 docker container
  tags: server, pgp, smime
  shell: docker restart misp-server


  