---
- name: MISP Installation Script for Docker
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False

  vars_files:
    - "/srv/misp-dockerized/config/misp.conf.yml"  

  pre_tasks:
  - name: read MISP Tag
    shell: "cat /srv/misp-dockerized/docker-compose.yml |grep dcso/misp-dockerized-server*|cut -d : -f 3|cut -d ' ' -f 1"
    register: MISP
    tags: always

  roles:
   - role: server
     tags: ['server']
   - role: database
     tags: ['database']
     #MISP_TAG: "{{ MISP.stdout }}"
   - role: proxy
     tags: ['proxy']

  tasks:
  - name: Ensure directories are 0755
    command: find {{ path }} -type d -exec chmod 0755 {} \;

  - name: Ensure files are 0644
    command: find {{ path }} -type f -exec chmod 0644 {} \;
    